server.port=8091

# Supabase PostgreSQL Connection
spring.datasource.url=jdbc:postgresql://ep-spring-meadow-apwood77-pooler.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_32DcBNZYPHtX
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
# Ya no es necesario especificar el dialecto (Hibernate lo detecta solo)


spring.jpa.show-sql=true

spring.thymeleaf.cache=false